#!/usr/bin/env bash
#
# helm-sync.sh — copy the two controller-gen-generated regions into the Helm
# chart. Run through `make helm-sync` (which runs `make manifests` first).
#
#   1. config/crd/bases/kvsynk8s.io_secretsyncs.yaml
#        -> charts/kvsynk8s/templates/crds/secretsync-crd.yaml
#      Wrapped in a `.Values.crds.install` gate, with a `.Values.crds.keep`-gated
#      `helm.sh/resource-policy: keep` annotation injected into metadata.annotations.
#
#   2. the `rules:` block of config/rbac/role.yaml
#        -> between the BEGIN/END markers in
#           charts/kvsynk8s/templates/rbac/manager-clusterrole.yaml
#
# Everything else in the chart is hand-maintained source. Output is byte-stable:
# running this twice in a row must leave `git diff charts/` clean, which is what
# the helm.yml workflow asserts (FR-015, SC-006).

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

CRD_SRC="config/crd/bases/kvsynk8s.io_secretsyncs.yaml"
CRD_DST="charts/kvsynk8s/templates/crds/secretsync-crd.yaml"
ROLE_SRC="config/rbac/role.yaml"
ROLE_DST="charts/kvsynk8s/templates/rbac/manager-clusterrole.yaml"

BEGIN_MARKER="# BEGIN generated rules (make helm-sync)"
END_MARKER="# END generated rules"

for f in "$CRD_SRC" "$ROLE_SRC" "$ROLE_DST"; do
  [ -f "$f" ] || { echo "helm-sync: missing input $f" >&2; exit 1; }
done

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

# ---------------------------------------------------------------------------
# 1. CRD template
# ---------------------------------------------------------------------------
mkdir -p "$(dirname "$CRD_DST")"

{
  cat <<'HEADER'
{{/*
GENERATED by `make helm-sync` from config/crd/bases/kvsynk8s.io_secretsyncs.yaml.
Do not edit by hand — change the Go types or kubebuilder markers and re-run
`make helm-sync`.

The CRD is a normal template rather than a file in Helm's special crds/
directory, because that directory is install-once: Helm never upgrades what it
contains and cannot template it, which rules out both CRD upgrades and the
crds.install / crds.keep gates (research.md R1).

  crds.install=false  the CRD is not rendered at all; the cluster must already
                      have it.
  crds.keep=true      the CRD carries helm.sh/resource-policy: keep, so
                      `helm uninstall` leaves it — and therefore every
                      SecretSync object — in place.
*/}}
{{- if .Values.crds.install }}
HEADER

  # Inject the keep-gated annotation into the metadata.annotations block that
  # controller-gen emits. If a future controller-gen stops emitting annotations
  # entirely, create the block instead of silently dropping the policy.
  awk '
    BEGIN { in_meta = 0; done = 0 }
    function emit_keep() {
      print "    {{- if .Values.crds.keep }}"
      print "    helm.sh/resource-policy: keep"
      print "    {{- end }}"
      done = 1
    }
    {
      if (!done && in_meta == 0 && $0 == "metadata:") { print; in_meta = 1; next }
      if (!done && in_meta == 1) {
        if ($0 == "  annotations:") { print; emit_keep(); next }
        # metadata has no annotations block: open one before the next key.
        print "  annotations:"
        emit_keep()
        print
        next
      }
      print
    }
    END {
      if (!done) {
        print "helm-sync: could not find metadata: in the CRD source" > "/dev/stderr"
        exit 1
      }
    }
  ' "$CRD_SRC"

  printf '%s\n' '{{- end }}'
} > "$tmpdir/crd.yaml"

mv "$tmpdir/crd.yaml" "$CRD_DST"

# ---------------------------------------------------------------------------
# 2. manager ClusterRole rules
# ---------------------------------------------------------------------------
grep -qxF "$BEGIN_MARKER" "$ROLE_DST" || { echo "helm-sync: $ROLE_DST has no BEGIN marker" >&2; exit 1; }
grep -qxF "$END_MARKER" "$ROLE_DST" || { echo "helm-sync: $ROLE_DST has no END marker" >&2; exit 1; }

# Everything from the top-level `rules:` key to the end of the generated role.
awk '/^rules:/ { found = 1 } found { print } END { if (!found) { print "helm-sync: no rules: block in role source" > "/dev/stderr"; exit 1 } }' \
  "$ROLE_SRC" > "$tmpdir/rules.yaml"

awk -v begin_marker="$BEGIN_MARKER" -v end_marker="$END_MARKER" -v rules="$tmpdir/rules.yaml" '
  $0 == begin_marker { print; skip = 1; while ((getline line < rules) > 0) print line; close(rules); next }
  $0 == end_marker   { skip = 0; print; next }
  !skip              { print }
' "$ROLE_DST" > "$tmpdir/role.yaml"

mv "$tmpdir/role.yaml" "$ROLE_DST"

echo "helm-sync: updated $CRD_DST and the generated rules region of $ROLE_DST"
