apiVersion: kvsynk8s.io/v1alpha1
kind: SecretSync
metadata:
  labels:
    app.kubernetes.io/name: kvsynk8s
    app.kubernetes.io/managed-by: kustomize
  name: secretsync-sample
spec:
  # TODO(user): Add fields here
